services:
  postgres:
    image: postgres:16
    container_name: classicmodels_db
    env_file:
        - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql:z
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d classicmodels"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
